server:
  port: 8090
  servlet:
    context-path: /learning

spring:
  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/learningdb?sslMode=REQUIRED
    username: 4LGbsrBLSmPw4K8.root
    password: yTj7fhI0tzERXGuC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

cloudinary:
  cloud-name: dabb0yavq
  api-key: 629417998313995
  api-secret: Pz7QaOBFl3nGzZVfWWmb2Vvx3DQ

external:
  process-video-url: https://satyr-dashing-officially.ngrok-free.app/process-video

services:
  identity:
    url: https://englishapp-backend-springboot-1.onrender.com/identity

